version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=2617
      - POSTGRES_USER=postgres
      - POSTGRES_DB=yurjinia

  redis:
    image: redis:7.0-alpine
    container_name: yurjinia_redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:80"   # Веб-інтерфейс MailDev доступний на порту 1080
      - "1025:1025" # SMTP-сервер MailDev слухає на порту 1025
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=80

volumes:
  redis_data:
