server:
  port: 9000

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/yurjinia
    username: postgres
    password: 2617
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 91165201794-3p5cukhiasac3he490khe4vgrrfqb7s1.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
              - openid
  mail:
    host: smtp.gmail.com
    port: 587
    username: yurjiniayur@gmail.com
    password: hvcuvdfmaafzbpba
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

aws:
  s3:
    bucket-name: yurjinia
    region: eu-north-1
  credentials:
    access-key-id: AWS_ACCESS_KEY_ID
    secret-access-key: AWS_SECRET_ACCESS_KEY

jwt:
  token:
    key: HvkjjOh2pmc28YGIQzCTFXCfGT6JLBhcwmx1oSJyeXE=
    expiration: 36000
    user-expiration: 604800
    validateTimeout: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
      web: DEBUG
      com.yurjinia: TRACE
      com.yurjinia.user.repository: ERROR
      com.yurjinia.common.security.jwt.filters.JwtAuthenticationFilter: WARN
    root: info

